### ISSUE TITLE
[Challenge] Lucky draw

### ISSUE THREAD

**Issue by kevin940726** [kevin940726/challenges#4]
## Name
lucky-draw

## Description
It's near the time when we have year-end party or spring party in Taiwan. There're often lucky draw events during the party. Please create a lucky draw application to help the organizers for such events.

An example app can be found [here](https://lab.sp88.com.tw/luckydraw/). Although the custom title is not required.

The style of the app is entirely up to the challenger to decide. However, they're not required and will not be in the acceptance criteria.

## Suggested Difficulty
medium

## Estimated time
1 day ~ 3 days

## Acceptance criteria

- Users should be able to paste in poll list or create serial number automatically.
- Users should be able to select how many winners there would be.
- The draw should be as random as possible.
- No external library to handle the random functionality.

## Bonus
- Tests
- Documentation

**Comment by escapiststupor** [comment]
要做那個亂數動畫嗎 :trollface:

**Comment by kevin940726** [comment]
That's just an example app, styles are all optional and not the main points here.

**Comment by escapiststupor** [comment]
選我選我
